# Generated by Django 2.2.28 on 2025-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoeats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorites',
            name='favorite_restaurant',
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='favorite_restaurant',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='djangoeats.Restaurant'),
        ),
    ]
