# Generated by Django 2.2.28 on 2025-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoeats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('drink', 'Drink')], max_length=20),
        ),
    ]
