# Generated by Django 2.2.28 on 2025-03-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoeats', '0002_auto_20250317_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorites',
            old_name='favorite_restaurant',
            new_name='favorite_restaurants',
        ),
    ]
