# Generated by Django 2.2.28 on 2025-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoeats', '0003_auto_20250317_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='djangoeats.Restaurant'),
        ),
        migrations.DeleteModel(
            name='UserFavorites',
        ),
    ]
