# Generated by Django 2.2.28 on 2025-03-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoeats', '0009_auto_20250322_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
    ]
